spring:
  h2.console:
    enabled=: true
    path: '/console'


  datasource:
    url: 'jdbc:h2:~/Users/Xeon/IdeaProjects/portfolio-ante-app/project-db'

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true